### ISSUE TITLE
Missing Header File

### ISSUE THREAD

**Issue by wyosae67** [freefloating-gazebo/freefloating_gazebo_demo#1]
freefloating_gazebo/BodySetpoint.h is missing.  Cannot compile the demo

**Comment by wyosae67** [comment]
improper workspace settings

**Comment by cmcghan** [comment]
BodySetpoint.h is created from BodySetpoint.msg in freefloating-gazebo/freefloating_gazebo
If you don't re-source the catkin workspace after catkin_make'ing that package and trying to compile the demo, then catkin_make won't find the file.

Once the ROS message has been made via catkin_make at least once, it will exist in the catkin_ws/devel directory to be able to be found.

Explicit instructions (this assumes you already have a ROS desktop installation and a catkin workspace set up):
$ cd catkin_ws
$ source /opt/ros/indigo/setup.bash
$ source devel/setup.bash
$ cd src
$ git clone https://github.com/freefloating-gazebo/freefloating_gazebo
$ git clone https://github.com/freefloating-gazebo/freefloating_gazebo_demo
$ cd ..
$ catkin_make
(You might need to source devel/setup.bash and run catkin_make twice.)
Have fun! :)
