### ISSUE TITLE
Missing texture and part3 in Gazebo

### ISSUE THREAD

**Issue by tomlogan501** [freefloating-gazebo/freefloating_gazebo_demo#5]
Hi,
I follow the tutorial to get the running demo in gazebo and I obtain this 
![missing](https://user-images.githubusercontent.com/56969577/76395486-b492d080-6377-11ea-8faa-27eb8056fff9.png)

Otherwise, the demo seems to work, should it grasp the black box every time ?
I'm using Gazebo9 on ROS Melodic from src

**Comment by oKermorgant** [comment]
Hi, 
Yes the original mesh files I had are the .osg for UWSim. They do not display well in Gazebo (no colors, and even nothing visible for this link). 

As for the demo, my experience is that the black box is not grasped everytime, possibly because of simulation time.

**Comment by Jeongshi** [comment]
Hello, I want to give the robot a trial run on ROS2. But it keeps failing, do you have any suggestions, thank you.

**Comment by oKermorgant** [comment]
Hi,

This repo is archived and there are no plans to use it in ROS 2.
Ignition / GazeboSim now has [builtin hydrodynamics and thruster plugins](https://gazebosim.org/api/gazebo/5.0/underwater_vehicles.html), this is the way you should go.
